name: PLPickup
description: Special plugin for Prison Life project
main: ru.rntsdkv.plpickup.Main
version: 1.0
commands:
  pickup:
    description: Main command of plugin
    usage: To set new pickup: /pickup set <block ID> <name> <text>
    To show list of pickups: /pickup list
    To teleport to pickup: /pickup tp <name>
    To delete pickup: /pickup delete <name>