name: PLPickup
main: ru.prisonlife.plpickup.Main
version: 1.0
description: Special plugin for Prison Life project

author: rntsdkv

commands:
  pickup:
    description: Main command of plugin
    permission: plpickup.pickup
    usage:
      To set new pickup: /pickup set <block ID> <name> <text>
      To show list of pickups: /pickup list
      To teleport to pickup: /pickup tp <name>
      To delete pickup: /pickup delete <name>