name: PLPickup
main: ru.prisonlife.plpickup.Main
version: v1.10
author: rntsdkv
commands:
  pickup set:
    description: Create new pickup
    permission: plpickup.set
    usage: /pickup set <block ID> <name> <text>
  pickup delete:
    description: Delete pickup
    permission: plpickup.delete
    usage: /pickup delete <name>
  pickup info:
    description: Show info about pickup
    permission: plpickup.info
    usage: /pickup info <name>
  pickup list:
    description: Show all created pickups
    permission: plpickup.list
    usage: /pickup list
  pickup tp:
    description: Teleport to pickup
    permission: plpickup.tp
    usage: /pickup tp <name>